### ISSUE TITLE
MMPQ2222A availability

### ISSUE THREAD

**Issue by leifj** [ea3igt/HL2-PA70#2]
the MMPQ2222A is pretty much unobtainium now. I tried to do a jlcpcb run and those quad arrays don't seem to exist. A quick equivalence search on Farnell turn up the [MMPQ3904](https://ie.farnell.com/on-semiconductor/mmpq3904/trans-bipol-npn-quad-40v-soic/dp/2454040) but those have slightly different specs.

1. Would the MMPQ3904 likely work?
2. Is there an alternative component?

**Comment by ea3igt** [comment]
Any generic NPN transistor will do the job, as it works as a switch, driving the signal to ground. I think this MMPQ3904 will work
